import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

if __name__ == "__main__":
    # create the colormap for the attractor
    colors = ['#f1f1f1', '#c8f7f6', '#acdad9', '#8fbcbb', '#689493', '#568281', '#335e5d']
    cmap = LinearSegmentedColormap.from_list('blueish', colors)

    # load the data generated by Rust
    x, y, z = np.loadtxt('./data/points.csv', delimiter=',', unpack=True)

    dpi = 350
    fig = plt.figure(figsize=(16, 9), dpi=dpi)
    ax = plt.axes(projection='3d')
    ax.set_facecolor('#2e3440')

    # ax.scatter(x, y, z, c = x + y + z, s=0.02, marker='.', cmap='Greys')
    # ax.scatter(x, y, z, c = '#8fbcbb', s=0.02, marker='o')
    ax.scatter(x, y, z, c=x + y + z, s=0.02, marker='.', cmap=cmap)
    plt.tight_layout()
    plt.subplots_adjust(left=0, right=1, top=1, bottom=0.)
    plt.axis('off')
    plt.savefig('./data/attractor.png', bbox_inches='tight', dpi=dpi, pad_inches=0)
